# server properties
server:
  port: 8082
  servlet:
    context-path: /api/process-pension
# spring properties
spring:
  application:
    name: PROCESS-PENSION-SERVICE 
    
# Configure Database here
  datasource:
    url: jdbc:h2:mem:process_pension_db
    username: rounak  
    password: rounak
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # add public IP link here
      defaultZone: http://localhost:8761/eureka/ 
      
logging:
  level:
    '[org.springframework.web]': ERROR
    '[com.cts.processPension]': DEBUG       