# server properties
server:
 port: 8083
 servlet:
    context-path: /api/pensioner-detail
# spring properties
spring:
 application:
  name: PENSIONER-DETAIL-SERVICE
  
#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # add public IP link here
      defaultZone: http://localhost:8761/eureka/ 

# Error Messages
errorMessage: Aadhaar Number Not Found

logging:
 level:
    '[org.springframework.web]': ERROR
    '[com.cts.pensionerDetails]': DEBUG     